#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UWA.AndroidClient.Resource", IsApplication=true)]

namespace UWA.AndroidClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::UWA.Core.MonoAndroid.Resource.String.ApplicationName = global::UWA.AndroidClient.Resource.String.ApplicationName;
			global::UWA.Core.MonoAndroid.Resource.String.Hello = global::UWA.AndroidClient.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_search = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_view_as_list = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ico_forward = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int uwa_logo_240 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int uwa_logo_480 = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int action_places = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int action_search = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int btnImgForward = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int description = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int eventIcon = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int eventListView = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int eventsButton = 2131165193;
			
			// aapt resource value: 0x7f070006
			public const int logo = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int logoLabel = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int mapButton = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int name = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int office = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int peopleButton = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int peopleListView = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int pubDate = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Events = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EventsListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Map = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int People = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PeopleListItem = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MapMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int Hmm = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int action_listLocations = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int action_searchLocations = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int app_label = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int eventsButtonText = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int google_APIkey_debug = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int locationsPlaceholder = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int logo_label = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int mapButtonText = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int peopleButtonText = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int search_hint = 2131034121;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int searchable = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
